default_provider = "age"

[providers.age]
type = "age"
recipients = ["age1nlqfv0ptcfs7ssuuq8c06nprslcvwg9qpt6kf0ex20jhnknjmsqsrqf96k", "age1jm5g49tr96kf9qfhwurpkp3f6npucueec4q065pzrqux73d5qe0skawf43"]

[secrets]
CLOUDFLARE_ACCOUNT_ID= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TVdMVmNvaHc1S2srQUc5elMyb0VkL2VFc2tBNW9PV0NBeEsyNHd5czNzCkdIS2pLbnIrUFhjSzRkTE9melE4dUp1MCtwRXdTRHRDeUIzcTNWcEdIM28KLT4gWDI1NTE5IHcvV0VZVDVvV1pHWE1PaE5reitKdll2a3dhVktkTTF4aFZtc2FaVVV4bTQKZEdXZDd2ejJGd0tiNDUzUHZuYy9OWEJNd0VydHVTRFF1bFF4SW1EdTBtYwotPiBKITgrLWdyZWFzZSBtZiQgaSp8SX1vRDMgaDs+aDM3OQpnRkZUSE1wQ3hwdG0wWk4xTzdGRTIrRFE5VTUwMjhaMWRJS2svbGtaTWR4My9GazdYRDh2ODV4WmNEZGxoS1RHCk1qRVBPdHU4MnFtMXMxZlFMMlFqMUtiMHNieDYKLS0tIDQ5Y3RBWHY0dE5jYXZFSGpGbUlLMXU5bWN4dWszb0xiMGlXN0gzd2ZVNkEKnzep0EaFqew2rYbGmuxXde8597lUXp36/6DqqR38amEEII0FVYWQ7Qu4ChHz/mHh489hTf5rFcrMAYH96dLyHQ==" }
