# Monorepo =====================================================================

monorepo_root = true
[monorepo]
config_roots = ["pkgs/*"]

[tools]

# Stack ========================================================================

# Node.js
node = "lts"
"npm:pnpm" = "latest"

# Release
git-cliff = "latest"

# Build
sccache = "latest"


# Settings =====================================================================

[settings]
lockfile = true
idiomatic_version_file_enable_tools = ["rust"] # Use rust-toolchain.toml


# Tasks ========================================================================

[tasks.install]
depends = ["install/pnpm"]

[tasks."install/pnpm"]
run = "pnpm install"
