# Monorepo =====================================================================

monorepo_root = true
[monorepo]
config_roots = ["pkgs/*"]

[tools]

# Stack ========================================================================

# Node.js
node = "lts"
pnpm = "latest"


# Settings =====================================================================

[settings]
idiomatic_version_file_enable_tools = ["rust"] # Use rust-toolchain.toml
