name: Save Target Cache
description: Save the Cargo target cache.

inputs:
  target-key:
    required: true
    description: Key segment used for the Cargo target cache.

runs:
  using: composite

  steps:
    - name: Lookup Target Cache
      id: lookup-target
      uses: actions/cache/restore@v5
      with:
        path: target
        key: target-${{ runner.os }}-${{ inputs.target-key }}-${{ github.sha }}
        lookup-only: true

    - name: Save Target Cache
      if: ${{ steps.lookup-target.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v5
      with:
        path: target
        key: target-${{ runner.os }}-${{ inputs.target-key }}-${{ github.sha }}
